version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: echo "Installing node packages"
      - run: yarn
      - run: yarn build
  test:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: echo "Installing node packages"
      - run: yarn
      - run: echo "Testing"
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run:
        name: Deploy Master to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
