version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: echo "Installing node packages"
      - run: yarn
      - run: yarn build
  test:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: echo "Installing node packages"
      - run: yarn
      - run: echo "Testing"
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: echo 'Deploy'
      - run:
          name: Deploy Master to Heroku
          command: |
            yarn |
            yarn build |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - test
            - build
