version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: echo "Installing node packages"
      - run: yarn
  test:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: echo "Testing"
      - run: yarn test
workflows:
  version: 2
  install_test:
    jobs:
      - build
      - test
